// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Net5.R.InfraAlu.Data.Contexts;

namespace Net5.R.InfraAlu.Data.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collection", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Net5.R.InfraAlu.Data.Entities.Alumnos", b =>
                {
                    b.Property<Guid>("AlumnosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AlumnosId");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("Net5.R.InfraAlu.Data.Entities.course", b =>
                {
                    b.Property<Guid>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AlumnosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("Final")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Parcial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ScoreFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("courseName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("courseId");

                    b.HasIndex("AlumnosId");

                    b.ToTable("course");
                });

            modelBuilder.Entity("Net5.R.InfraAlu.Data.Entities.course", b =>
                {
                    b.HasOne("Net5.R.InfraAlu.Data.Entities.Alumnos", "Alumnos")
                        .WithMany("Courses")
                        .HasForeignKey("AlumnosId")
                        .HasConstraintName("FK_courseAlumnos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("Net5.R.InfraAlu.Data.Entities.Alumnos", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
